export const employeeData = [
	{
		name: "Thomas Wayne",
		jobTitle: "Desk manager",
		description: "Lorem ipsum",
		schedule: "Tuesday, Friday, Sunday",
		time: "08:00 - 16:00",
		contact: "123456789",
		status: "Active",
	},
	{
		name: "Steve Rogers",
		jobTitle: "Janitor",
		description: "Lorem ipsum",
		schedule: "Monday, Wednesday, Friday",
		time: "08:00 - 16:00",
		contact: "123456789",
		status: "Active",
	},

	{
		name: "Leonard Snard",
		jobTitle: "Help Desk",
		description: "Lorem ipsum",
		schedule: "Monday, Tuesday, Saturday",
		time: "08:00 - 16:00",
		contact: "123456789",
		status: "Active",
	},
	{
		name: "Hello World",
		jobTitle: "Security",
		description: "Lorem ipsum",
		schedule: "Tuesday, Friday, Sunday",
		time: "08:00 - 16:00",
		contact: "123456789",
		status: "Inactive",
	},
	{
		name: "Martha Wayne",
		jobTitle: "Desk manager",
		description: "Lorem ipsum",
		schedule: "Monday, Thursday, Friday",
		time: "08:00 - 16:00",
		contact: "123456789",
		status: "Active",
	},
	{
		name: "Thomas Wayne",
		jobTitle: "Sheldon Cooper",
		description: "Lorem ipsum",
		schedule: "Tuesday, Friday, Sunday",
		time: "08:00 - 16:00",
		contact: "123456789",
		status: "Active",
	},
	{
		name: "Barry Allen",
		jobTitle: "Desk manager",
		description: "Lorem ipsum",
		schedule: "Tuesday, Thursday, Sunday",
		time: "08:00 - 16:00",
		contact: "123456789",
		status: "Inactive",
	},
];
